steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        
        gcloud config set account engine@cloudbuild-386519.iam.gserviceaccount.com
        
        # Set the service account for subsequent steps
        gcloud auth activate-service-account --key-file=projects/645849086777/secrets/cloudbuild_json/versions/1
       

  - name: 'hashicorp/terraform:latest'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        
        export GOOGLE_APPLICATION_CREDENTIALS=projects/645849086777/secrets/cloudbuild_json/versions/1
        
        # Initialize Terraform
        terraform init

        # Plan the changes
        terraform plan -out=tfplan
        
        terraform apply tfplan


