
steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |

        echo "$_CLOUDBUILD_KEY" > /cloudbuild_key.json
        gcloud auth activate-service-account --key-file=/dev/stdin <<< "$_CLOUDBUILD_KEY"

        # Set the project ID
        gcloud config set project cloudbuild-386914
        
        # Remove the service account key file
        rm /cloudbuild_key.json
  
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'sh'
    args:
      - '-c'
      - |

        # Initialize Terraform
        terraform init

        # Plan the changes
        terraform plan -out=tfplan

        # Show the Terraform plan
        terraform show tfplan

#options:
 # logging: CLOUD_LOGGING_ONLY
