steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        
        gcloud config set account newbuild@cloudbuild-386519.iam.gserviceaccount.com
        
        # Set the service account for subsequent steps
        gcloud auth activate-service-account --key-file=cloudbuild.json

        # Set the project ID
        gcloud config set project cloudbuild-386519

  - name: 'hashicorp/terraform:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Initialize Terraform
        terraform init

        # Plan the changes
        terraform plan -out=tfplan


