steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Fetch the buildkey secret
        gcloud secrets versions access 2 --secret=projects/645849086777/secrets/buildkey --format='get(payload.data)' | base64 -d > /workspace/buildkey.json

        # Set the service account for subsequent steps
        gcloud config set account cloudbuild@cloudbuild-386519.iam.gserviceaccount.com

        # Set the project ID
        gcloud config set project cloudbuild-386519

  - name: 'hashicorp/terraform:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Initialize Terraform
        terraform init

        # Plan the changes
        terraform plan -out=tfplan

volumes:
  - name: 'secrets'
    path: '/workspace'

