steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Fetch the buildkey secret
        export BUILDKEY_CONTENT=$(gcloud secrets versions access 2 --secret=projects/645849086777/secrets/buildkey --format='get(payload.data)')

        # Decode the base64-encoded secret content
        export BUILDKEY_JSON=$(echo "$BUILDKEY_CONTENT" | base64 -d)

        # Create a temporary key file
        echo "$BUILDKEY_JSON" > /workspace/buildkey.json

        # Set the project ID
        gcloud config set project cloudbuild-386519

  - name: 'hashicorp/terraform:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Initialize Terraform
        terraform init

        # Plan the changes
        terraform plan -out=tfplan

substitutions:
  _BUILDKEY_CONTENT: /workspace/buildkey.json
