steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        
        gcloud config set account engine@cloudbuild-386519.iam.gserviceaccount.com
        
        # Set the service account for subsequent steps
        gcloud auth activate-service-account --key-file=cloudbuild.json

        # Set the project ID
       

  - name: 'hashicorp/terraform:latest'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        
        export GOOGLE_APPLICATION_CREDENTIALS=cloudbuild.json
        
        # Initialize Terraform
        terraform init

        # Plan the changes
        terraform plan -out=tfplan
        
        terraform apply tfplan


