
steps:
  - id: 'tf-init'
    name: 'hashicorp/terraform:latest'
    entrypoint: 'bash'
    args:
      - 'init'
    env:
      - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID'  
        
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'sh'
    args:
      - '-c'
      - |

        # Plan the changes
        terraform plan -out=tfplan

        # Show the Terraform plan
        terraform show tfplan
    env:
      - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID'
    waitFor: ['tf-init']


#options:
 # logging: CLOUD_LOGGING_ONLY
