steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Fetch the buildkey secret
        export BUILDKEY_CONTENT=$(gcloud secrets versions access latest --secret=buildkey)

        # Create a temporary key file
        echo "$BUILDKEY_CONTENT" > /tmp/buildkey.json

        # Authenticate with Google Cloud using the temporary key file
        gcloud auth activate-service-account --key-file=/tmp/buildkey.json

        # Set the project ID
        gcloud config set project arjun-cts-sandbox

  - name: 'hashicorp/terraform:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Initialize Terraform
        terraform init

        # Plan the changes
        terraform plan -out=tfplan
