steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Authenticate with Google Cloud
        gcloud auth activate-service-account --key-file=projects/645849086777/secrets/buildkey

        # Set the project ID
        gcloud config set project arjun-cts-sandbox

  - name: 'hashicorp/terraform:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Initialize Terraform
        terraform init

        # Plan the changes
        terraform plan -out=tfplan
