
steps:
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
          
        gcloud config set project cloudbuild-386914

        # Initialize Terraform
        terraform init

        # Plan the changes
        terraform plan -out=tfplan

        terraform apply tfplan
options:
  logging: CLOUD_LOGGING_ONLY
