steps:
  - id: 'tf-init'
    name: 'hashicorp/terraform:1.3.5'
    args:
      - 'init'
    env:
      - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID'

  - id: 'check-backend-state'
    name: 'hashicorp/terraform:1.3.5'
    args:
      - 'init'
      - '-backend-config=bucket=tf-state${var.project}'
    env:
      - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID'

  - id: 'tf-plan'     
    name: 'hashicorp/terraform:1.3.5'
    args:
      - 'plan'
      - '-lock=false'
      - '-out=tfplan'
    env:
      - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID'
    waitFor: ['tf-init']

  - id: 'tf-apply'
    name: 'hashicorp/terraform:1.3.5'
    args:
      - 'apply'
      - '-auto-approve'
    env:
      - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID'
    waitFor: ['tf-plan']

options:
  logging: LEGACY

