---
substitutions:
  _TERRAFORM_VERSION: '1.3.5'
timeout: '3600s'
steps:
  - id: 'tf-init'
    name: 'hashicorp/terraform:${_TERRAFORM_VERSION}'
    args:
      - 'init'
    env:
      - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID'  

  - id: 'tf-plan'     
    name: 'hashicorp/terraform:${_TERRAFORM_VERSION}'
    args:
      - 'plan'
      - '-lock=false'
    env:
      - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID'
    waitFor: ['tf-init']




