steps:
  - id: 'tf-init'
    name: 'hashicorp/terraform:1.3.5'
    args:
      - 'init'
    env:
      - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID'

  - id: 'check-backend-state'
    name: 'hashicorp/terraform:1.3.5'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'terraform init -backend-config="bucket=tf-state-arj-1"'
    env:
      - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID'    

  - id: 'tf-plan'     
    name: 'hashicorp/terraform:1.3.5'
    args:
      - 'plan'
      - '-lock=false'
      - '-out=tfplan'
    env:
      - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID'
    waitFor: ['tf-init']

  - id: 'display-tfplan'
    name: 'hashicorp/terraform:1.3.5'
    args:
      - 'show'
      - 'tfplan'
    env:
      - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID'

options:
  logging: CLOUD_LOGGING_ONLY
